/**
 * @file protobuffer_loader.h
 * @brief Provides a generic loading mechanism from Protobuf messages to VTX native structures using a SchemaRegistry.
 * @author Zenos Interactive
 */

#pragma once
#include <google/protobuf/message.h>
#include <vtx/common/readers/schema_reader/schema_registry.h>
#include "vtx/common/vtx_types.h"
#include "vtx/common/vtx_types_helpers.h"

namespace VTX {

    // Forward declaration for the binding logic used by the loader
    template <typename ProtoType>
    struct ProtoBinding;

    /**
     * @class GenericProtobufLoader
     * @brief Orchestrates the transfer of data from Protobuf objects to VTX PropertyContainers.
     * * This class uses a SchemaRegistry to map Protobuf fields to specific indices and types 
     * in the native VTX data structures, supporting nested structs, arrays, and primitive types.
     */
    class GenericProtobufLoader {
    private:
        const SchemaRegistry* schema_; ///< Reference to the schema mapping for type_max_indices/field resolution.
        bool debug_mode_;              ///< If true, logs warnings and loading steps to stdout.

    public:
        /**
         * @brief Constructs a new Generic Protobuf Loader.
         * @param schema The registry containing field and type metadata.
         * @param debug Enable or disable debug logging.
         */
        explicit GenericProtobufLoader(const SchemaRegistry& schema, bool debug = false)
            : schema_(&schema)
            , debug_mode_(debug) {}

        /**
         * @brief Loads data from a Protobuf message into a native PropertyContainer.
         * @tparam ProtoType The Protobuf message type generated by protoc.
         * @param src The source Protobuf message.
         * @param dest The target PropertyContainer to populate.
         * @param struct_name The name of the structure in the SchemaRegistry.
         */
        template <typename ProtoType>
        void Load(const ProtoType& src, PropertyContainer& dest, const std::string& struct_name) {
            if (debug_mode_) {
                std::cout << "[LOADER] Loading Struct: " << struct_name << "\n";
            }
            dest.entity_type_id = schema_->GetStructTypeId(struct_name);
            ProtoBinding<ProtoType>::Transfer(src, dest, *this, struct_name);
            dest.content_hash = Helpers::CalculateContainerHash(dest);
        }

        /**
         * @brief Loads a high-level Frame Protobuf message into a VTX::Frame.
         * @tparam FrameProtoType The Protobuf type representing a full data frame.
         * @param src The source Frame Protobuf message.
         * @param dest The target VTX::Frame object.
         * @param schemaName The registry name for the frame schema.
         */
        template <typename FrameProtoType>
        void LoadFrame(const FrameProtoType& src, VTX::Frame& dest, const std::string& schemaName) {
            ProtoBinding<FrameProtoType>::TransferToFrame(src, dest, *this, schemaName);
        }

        /**
         * @brief Appends a list of actors/entities from a repeated Protobuf field to a Data block.
         * @tparam RepeatedProtoType A Protobuf repeated field or container.
         * @tparam IdExtractorFunc A functor or lambda to extract a unique ID string from the ProtoType.
         * @param targetBlock The VTX::Data block where entities will be added.
         * @param schemaType The schema type name for the entities.
         * @param src_array The source container of Protobuf messages.
         * @param idExtractor Instance of the ID extractor function.
         */
        template <typename RepeatedProtoType, typename IdExtractorFunc>
        void AppendActorList(VTX::Bucket& targetBlock, const std::string& schemaType,
                             const RepeatedProtoType& src_array, IdExtractorFunc idExtractor) {
            if (src_array.empty())
                return;

            targetBlock.entities.reserve(targetBlock.entities.size() + src_array.size());

            for (const auto& item : src_array) {
                ExtractActorWithIdFunc(item, targetBlock, schemaType, idExtractor);
            }
        }

        /**
         * @brief Appends a single actor/entity to a Data block.
         * @tparam ProtoType The Protobuf message type.
         * @tparam IdExtractorFunc Functor to extract the unique ID.
         * @param targetBlock Target data block.
         * @param schemaType Schema type name.
         * @param src_item The source Protobuf message.
         * @param idExtractor The ID extractor function.
         */
        template <typename ProtoType, typename IdExtractorFunc>
        void AppendSingleActor(VTX::Bucket& targetBlock, const std::string& schemaType, const ProtoType& src_item,
                               IdExtractorFunc idExtractor) {
            ExtractActorWithIdFunc(src_item, targetBlock, schemaType, idExtractor);
        }

        /**
         * @brief Sets a single field value in a PropertyContainer based on schema metadata.
         * @tparam T The native C++ type of the value.
         * @param dest Target PropertyContainer.
         * @param struct_name Name of the parent structure in schema.
         * @param field_name Name of the field to set.
         * @param value The value to assign.
         * @note Performs type conversion and bounds checking via EnsureSize.
         */
        template <typename T>
        void LoadField(PropertyContainer& dest, const std::string& struct_name, const std::string& field_name,
                       const T& value) {
            const auto* field_info = schema_->GetField(struct_name, field_name);

            if (!field_info) {
                if (debug_mode_)
                    std::cout << "  [WARNING] Field not found: " << struct_name << "::" << field_name << "\n";
                return;
            }

            int32_t idx = field_info->index;
            VTX::FieldType target_type = field_info->type_id;

            if (debug_mode_) {
                std::cout << "  [SET] " << struct_name << "::" << field_name
                          << " (EnumID: " << static_cast<int>(target_type) << ")"
                          << " -> Index: " << idx << "\n";
            }

            switch (target_type) {
            case FieldType::String:
                StoreValue(dest.string_properties, idx, value);
                break;
            case FieldType::Int8:
            case FieldType::Int32:
            case FieldType::Enum:
                StoreValue(dest.int32_properties, idx, value);
                break;
            case FieldType::Int64:
                StoreValue(dest.int64_properties, idx, value);
                break;
            case FieldType::Float:
                StoreValue(dest.float_properties, idx, value);
                break;
            case FieldType::Double:
                StoreValue(dest.double_properties, idx, value);
                break;
            case FieldType::Bool:
                StoreValue(dest.bool_properties, idx, value);
                break;
            case FieldType::Vector:
                StoreValue(dest.vector_properties, idx, value);
                break;
            case FieldType::Quat:
                StoreValue(dest.quat_properties, idx, value);
                break;
            case FieldType::Transform:
                StoreValue(dest.transform_properties, idx, value);
                break;
            case FieldType::FloatRange:
                StoreValue(dest.range_properties, idx, value);
                break;
            case FieldType::Struct:
                StoreValue(dest.any_struct_properties, idx, value);
                break;
            case FieldType::None:
            default:
                break;
            }
        }

        /**
         * @brief Handles the loading of a nested Protobuf message into a recursive PropertyContainer.
         * @tparam NestedProtoType The type of the nested Protobuf message.
         * @param dest The parent PropertyContainer.
         * @param struct_name Name of the parent structure.
         * @param field_name Name of the field containing the nested struct.
         * @param src_nested The source nested Protobuf message.
         */
        template <typename NestedProtoType>
        void LoadStruct(PropertyContainer& dest, const std::string& struct_name, const std::string& field_name,
                        const NestedProtoType& src_nested) {
            const auto* field_info = schema_->GetField(struct_name, field_name);
            if (!field_info)
                return;

            int32_t index = field_info->index;
            std::string child_type_name = field_info->struct_type;

            if (debug_mode_) {
                std::cout << "  [STRUCT] " << struct_name << "::" << field_name << " -> Index: " << index
                          << " (SchemaType: " << child_type_name << ")"
                          << "\n";
            }

            EnsureSize(dest.any_struct_properties, index);
            Load(src_nested, dest.any_struct_properties[index], child_type_name);
        }

        /**
         * @brief Fills a flattened SoA (Structure of Arrays) from a repeated Protobuf primitive field.
         * @details Iterates through the source collection and uses the PushBack method of FlatArray
         * to maintain the data and offset integrity within the PropertyContainer.
         * @tparam RepeatedT A Protobuf repeated field or compatible container.
         * @param dest The target PropertyContainer holding the SoA structures.
         * @param type The VTX FieldType identifying the specific flat array to target.
         * @param idx The index of the logical sub-array within the FlatArray.
         * @param src The source collection of primitive values.
         */
        template <typename RepeatedT>
        void FillFlatArray(PropertyContainer& dest, FieldType type, int32_t idx, const RepeatedT& src) {
            for (const auto& val : src) {
                // Compile-time check: is the value a string-like type?
                constexpr bool is_string_type = std::is_convertible_v<decltype(val), std::string_view> ||
                                                std::is_same_v<std::decay_t<decltype(val)>, std::string>;

                switch (type) {
                case FieldType::Int8:
                case FieldType::Int32:
                case FieldType::Enum:
                    if constexpr (!is_string_type) {
                        dest.int32_arrays.PushBack(idx, static_cast<int32_t>(val));
                    } else {
                        if (debug_mode_)
                            std::cerr << "[LOADER] Error: Trying to cast a string to Int32 array.\n";
                    }
                    break;

                case FieldType::Int64:
                    if constexpr (!is_string_type) {
                        dest.int64_arrays.PushBack(idx, static_cast<int64_t>(val));
                    } else {
                        if (debug_mode_)
                            std::cerr << "[LOADER] Error: Trying to cast a string to Int64 array.\n";
                    }
                    break;

                case FieldType::Float:
                    if constexpr (!is_string_type) {
                        dest.float_arrays.PushBack(idx, static_cast<float>(val));
                    } else {
                        if (debug_mode_)
                            std::cerr << "[LOADER] Error: Trying to cast a string to Float array.\n";
                    }
                    break;

                case FieldType::Double:
                    if constexpr (!is_string_type) {
                        dest.double_arrays.PushBack(idx, static_cast<double>(val));
                    } else {
                        if (debug_mode_)
                            std::cerr << "[LOADER] Error: Trying to cast a string to Double array.\n";
                    }
                    break;

                case FieldType::Bool:
                    if constexpr (!is_string_type) {
                        dest.bool_arrays.PushBack(idx, static_cast<bool>(val));
                    } else {
                        if (debug_mode_)
                            std::cerr << "[LOADER] Error: Trying to cast a string to Bool array.\n";
                    }
                    break;

                case FieldType::String:
                    if constexpr (is_string_type) {
                        dest.string_arrays.PushBack(idx, std::string(val));
                    } else if constexpr (std::is_arithmetic_v<std::decay_t<decltype(val)>>) {
                        dest.string_arrays.PushBack(idx, std::to_string(val));
                    }
                    break;

                default:
                    if (debug_mode_) {
                        std::cerr << "[LOADER] FillFlatArray: FieldType " << static_cast<int>(type)
                                  << " is not a supported primitive for flat arrays.\n";
                    }
                    break;
                }
            }
        }

        /**
         * @brief Helper to push a complex math object that was temporarily loaded into its SoA FlatArray.
         * @details This is used when an array contains complex types (Vector, Quat, etc.) that the 
         * loader first processes into a single PropertyContainer before flattening them into the 
         * main SoA structure.
         * * @param dest The target PropertyContainer holding the SoA arrays.
         * @param type The VTX FieldType identifying which array to target.
         * @param idx The specific sub-array index within the FlatArray.
         * @param temp The temporary container where the single object was initially loaded.
         */
        void PushToFlatArray(PropertyContainer& dest, FieldType type, int32_t idx,
                             const PropertyContainer& temp) const {
            switch (type) {
            case FieldType::Vector:
                if (!temp.vector_properties.empty()) {
                    dest.vector_arrays.PushBack(idx, temp.vector_properties[0]);
                }
                break;

            case FieldType::Quat:
                if (!temp.quat_properties.empty()) {
                    dest.quat_arrays.PushBack(idx, temp.quat_properties[0]);
                }
                break;

            case FieldType::Transform:
                if (!temp.transform_properties.empty()) {
                    dest.transform_arrays.PushBack(idx, temp.transform_properties[0]);
                }
                break;

            case FieldType::FloatRange:
                if (!temp.range_properties.empty()) {
                    dest.range_arrays.PushBack(idx, temp.range_properties[0]);
                }
                break;

            case FieldType::Struct:
                if (temp.entity_type_id != -1) {
                    dest.any_struct_arrays.PushBack(idx, temp);
                }
                break;

            default:
                if (debug_mode_) {
                    std::cerr << "[LOADER] PushToFlatArray: Type " << static_cast<int>(type)
                              << " is not a complex math type_max_indices supported by SoA flattening.\n";
                }
                break;
            }
        }

        /**
         * @brief Serializes a repeated Protobuf field (array) into the appropriate VTX property array.
         * @tparam RepeatedProtoType A Protobuf container of elements.
         * @param dest Target PropertyContainer.
         * @param struct_name Parent structure name.
         * @param field_name Field name.
         * @param src_array The source collection of values/messages.
         */
        template <typename RepeatedProtoType>
        void LoadArray(PropertyContainer& dest, const std::string& struct_name, const std::string& field_name,
                       const RepeatedProtoType& src_array) {
            const auto* field_info = schema_->GetField(struct_name, field_name);
            if (!field_info || src_array.empty())
                return;

            using ElementT = typename RepeatedProtoType::value_type;
            const int32_t idx = field_info->index;

            if constexpr (std::is_base_of_v<google::protobuf::Message, ElementT>) {
                const std::string& child_schema = field_info->struct_type;

                for (const auto& item : src_array) {
                    if (field_info->type_id == FieldType::Struct) {
                        PropertyContainer child_container;
                        Load(item, child_container, child_schema);
                        dest.any_struct_arrays.PushBack(idx, child_container);
                    } else {
                        PropertyContainer temp;
                        Load(item, temp, child_schema);
                        PushToFlatArray(dest, field_info->type_id, idx, temp);
                    }
                }
            } else {
                FillFlatArray(dest, field_info->type_id, idx, src_array);
            }
        }

        /**
         * @brief Injects a memory block (Blob) directly into byte_array_properties
         */
        void LoadBlob(PropertyContainer& dest, const std::string& struct_name, const std::string& field_name,
                      const void* data, size_t byte_size) {
            const auto* field_info = schema_->GetField(struct_name, field_name);
            if (!field_info || byte_size == 0)
                return;

            const uint8_t* byte_data = static_cast<const uint8_t*>(data);

            for (size_t i = 0; i < byte_size; ++i) {
                dest.byte_array_properties.PushBack(field_info->index, byte_data[i]);
            }
        }

    private:
        /**
         * @brief Internal helper to load an actor and extract its ID.
         * @tparam ActorT Protobuf message type of the actor.
         * @tparam IdExtractorFunc ID extraction logic.
         * @param src Source actor message.
         * @param block Target data block.
         * @param schemaType Entity schema type.
         * @param idExtractor Function instance.
         */
        template <typename ActorT, typename IdExtractorFunc>
        void ExtractActorWithIdFunc(const ActorT& src, VTX::Bucket& block, const std::string& schemaType,
                                    IdExtractorFunc idExtractor) {
            PropertyContainer& entity = block.entities.emplace_back();
            Load(src, entity, schemaType);
            Helpers::CalculateContainerHash(entity);
            std::string uid = idExtractor(src);
            block.unique_ids.push_back(uid);
        }

        /**
         * @brief Internal utility to resize a vector to accommodate a specific index.
         * @tparam Vec Vector type.
         * @param v Vector reference.
         * @param index Desired index.
         */
        template <typename Vec>
        void EnsureSize(Vec& v, size_t index) {
            if (v.size() <= index) {
                v.resize(index + 1);
            }
        }

        template <typename Vec, typename V>
        void StoreValue(Vec& vector, size_t index, const V& val) {
            EnsureSize(vector, index);
            if constexpr (std::is_same_v<typename Vec::value_type, std::string> && std::is_arithmetic_v<V>)
                vector[index] = std::to_string(val);
            else if constexpr (std::is_assignable_v<typename Vec::value_type&, V>)
                vector[index] = static_cast<typename Vec::value_type>(val);
        }
    };
} // namespace VTX
