#pragma once
// arena_binary_mappings.h -- BinaryBinding<Tag> specializations that match
// the raw-binary layout produced by generate_replay.cpp::ExportBinarySource().
//
// The tags here (BinPlayer, BinProjectile, BinMatchState, BinArenaFrame) are
// empty marker structs used as discriminators for the BinaryBinding<>
// template -- there is no autogenerated type to dispatch on the way FB and
// Proto have (arena_fb::Player / arena_pb::Player). The order of cur.Read<>()
// calls in each Transfer MUST match the producer's write order; that order
// IS the schema for this loader.
//
// Driven by VTX::GenericBinaryLoader::Load / LoadFrame in
// samples/advance_write.cpp's ArenaBinaryDataSource.

#include <cstdint>
#include <string>

#include "vtx/common/adapters/binary/binary_cursor.h"
#include "vtx/common/readers/frame_reader/binary_loader.h"
#include "vtx/common/vtx_types.h"

#include "arena_generated.h"

// ===================================================================
//  Binary layout tags (discriminators for BinaryBinding<>)
// ===================================================================

struct BinPlayer {};
struct BinProjectile {};
struct BinMatchState {};
struct BinArenaFrame {};

// ===================================================================
//  Per-entity bindings
// ===================================================================
//  Each Transfer walks the cursor in producer order and feeds each value
//  into the right PropertyContainer slot via LoadField. The slot names
//  come from the autogenerated VTX::ArenaSchema::* constants -- a rename
//  in arena_schema.json is caught at compile time.

template <>
struct VTX::BinaryBinding<BinPlayer> {
    static void Transfer(VTX::BinaryCursor& cur, VTX::PropertyContainer& dest, VTX::GenericBinaryLoader& loader,
                         const std::string& schema) {
        namespace P = VTX::ArenaSchema::Player;

        loader.LoadField(dest, schema, P::UniqueID, cur.ReadLenString<uint16_t>());
        loader.LoadField(dest, schema, P::Name, cur.ReadLenString<uint16_t>());
        loader.LoadField(dest, schema, P::Team, cur.Read<int32_t>());
        loader.LoadField(dest, schema, P::Health, cur.Read<float>());
        loader.LoadField(dest, schema, P::Armor, cur.Read<float>());

        VTX::Vector pos {cur.Read<double>(), cur.Read<double>(), cur.Read<double>()};
        loader.LoadField(dest, schema, P::Position, pos);

        VTX::Quat rot {cur.Read<float>(), cur.Read<float>(), cur.Read<float>(), cur.Read<float>()};
        loader.LoadField(dest, schema, P::Rotation, rot);

        VTX::Vector vel {cur.Read<double>(), cur.Read<double>(), cur.Read<double>()};
        loader.LoadField(dest, schema, P::Velocity, vel);

        loader.LoadField(dest, schema, P::IsAlive, cur.Read<uint8_t>() != 0);
        loader.LoadField(dest, schema, P::Score, cur.Read<int32_t>());
        loader.LoadField(dest, schema, P::Deaths, cur.Read<int32_t>());
    }
};

template <>
struct VTX::BinaryBinding<BinProjectile> {
    static void Transfer(VTX::BinaryCursor& cur, VTX::PropertyContainer& dest, VTX::GenericBinaryLoader& loader,
                         const std::string& schema) {
        namespace P = VTX::ArenaSchema::Projectile;

        loader.LoadField(dest, schema, P::UniqueID, cur.ReadLenString<uint16_t>());
        loader.LoadField(dest, schema, P::OwnerID, cur.ReadLenString<uint16_t>());

        VTX::Vector pos {cur.Read<double>(), cur.Read<double>(), cur.Read<double>()};
        loader.LoadField(dest, schema, P::Position, pos);

        VTX::Vector vel {cur.Read<double>(), cur.Read<double>(), cur.Read<double>()};
        loader.LoadField(dest, schema, P::Velocity, vel);

        loader.LoadField(dest, schema, P::Damage, cur.Read<float>());
        loader.LoadField(dest, schema, P::Type, cur.ReadLenString<uint16_t>());
    }
};

template <>
struct VTX::BinaryBinding<BinMatchState> {
    static void Transfer(VTX::BinaryCursor& cur, VTX::PropertyContainer& dest, VTX::GenericBinaryLoader& loader,
                         const std::string& schema) {
        namespace M = VTX::ArenaSchema::MatchState;

        loader.LoadField(dest, schema, M::UniqueID, cur.ReadLenString<uint16_t>());
        loader.LoadField(dest, schema, M::ScoreTeam1, cur.Read<int32_t>());
        loader.LoadField(dest, schema, M::ScoreTeam2, cur.Read<int32_t>());
        loader.LoadField(dest, schema, M::Round, cur.Read<int32_t>());
        loader.LoadField(dest, schema, M::Phase, cur.ReadLenString<uint16_t>());
        loader.LoadField(dest, schema, M::TimeRemaining, cur.Read<float>());
    }
};

// ===================================================================
//  Frame binding -- builds the VTX::Frame buckets
// ===================================================================
//  This is the entry point called by GenericBinaryLoader::LoadFrame. The
//  data source has already consumed the per-frame header (frame_index,
//  game_time, utc_ticks) before reaching us, so the cursor sits at
//  PLAYER_COUNT. We read counts + bodies and push each entity into the
//  "entity" bucket.
//
//  The unique_id of each entity is recovered from string_properties[0]
//  AFTER Load -- the schema guarantees UniqueID is the first string slot
//  for Player, Projectile and MatchState.

template <>
struct VTX::BinaryBinding<BinArenaFrame> {
    static void TransferToFrame(VTX::BinaryCursor& cur, VTX::Frame& dest, VTX::GenericBinaryLoader& loader,
                                const std::string& /*schema_name*/) {
        dest = VTX::Frame {};
        VTX::Bucket& bucket = dest.GetBucket("entity");
        bucket.entities.clear();
        bucket.unique_ids.clear();

        const uint32_t player_count = cur.Read<uint32_t>();
        for (uint32_t i = 0; i < player_count; ++i) {
            auto& pc = bucket.entities.emplace_back();
            loader.Load<BinPlayer>(cur, pc, VTX::ArenaSchema::Player::StructName);
            bucket.unique_ids.push_back(pc.string_properties.front());
        }

        const uint32_t proj_count = cur.Read<uint32_t>();
        for (uint32_t i = 0; i < proj_count; ++i) {
            auto& pc = bucket.entities.emplace_back();
            loader.Load<BinProjectile>(cur, pc, VTX::ArenaSchema::Projectile::StructName);
            bucket.unique_ids.push_back(pc.string_properties.front());
        }

        auto& mc = bucket.entities.emplace_back();
        loader.Load<BinMatchState>(cur, mc, VTX::ArenaSchema::MatchState::StructName);
        bucket.unique_ids.push_back(mc.string_properties.front());
    }
};
