// =============================================================================
// Autogenerated code by vtx_codegen.py! DO NOT MODIFY!
// =============================================================================
#pragma once
#include <string>
#include <cstdint>
#include <span>
#include "vtx/common/vtx_property_cache.h"
#include "vtx/reader/core/vtx_frame_accessor.h"

namespace VTX::ArenaSchema {

    /** @brief Strongly typed IDs for all entities in the schema */
    enum class EntityType : int32_t {
        Player = 0,
        Projectile = 1,
        MatchState = 2,
        Unknown = -1
    };

    namespace Player {
        constexpr const char* StructName = "Player";
        constexpr const char* UniqueID = "UniqueID";
        constexpr const char* Name = "Name";
        constexpr const char* Team = "Team";
        constexpr const char* Health = "Health";
        constexpr const char* Armor = "Armor";
        constexpr const char* Position = "Position";
        constexpr const char* Rotation = "Rotation";
        constexpr const char* Velocity = "Velocity";
        constexpr const char* IsAlive = "IsAlive";
        constexpr const char* Score = "Score";
        constexpr const char* Deaths = "Deaths";
    }

    class PlayerView {
    private:
        VTX::EntityView data_view;
        const VTX::FrameAccessor& accessor;

    public:
        PlayerView(VTX::EntityView view, const VTX::FrameAccessor& acc) 
            : data_view(view), accessor(acc) {}

        PlayerView(const VTX::PropertyContainer& container, const VTX::FrameAccessor& acc) 
            : data_view(container), accessor(acc) {}

        inline const std::string& GetUniqueID() const {
            static VTX::PropertyKey<std::string> cached_key = accessor.Get<std::string>(EntityType::Player, Player::UniqueID);
            return data_view.Get<std::string>(cached_key);
        }

        inline const std::string& GetName() const {
            static VTX::PropertyKey<std::string> cached_key = accessor.Get<std::string>(EntityType::Player, Player::Name);
            return data_view.Get<std::string>(cached_key);
        }

        inline int32_t GetTeam() const {
            static VTX::PropertyKey<int32_t> cached_key = accessor.Get<int32_t>(EntityType::Player, Player::Team);
            return data_view.Get<int32_t>(cached_key);
        }

        inline float GetHealth() const {
            static VTX::PropertyKey<float> cached_key = accessor.Get<float>(EntityType::Player, Player::Health);
            return data_view.Get<float>(cached_key);
        }

        inline float GetArmor() const {
            static VTX::PropertyKey<float> cached_key = accessor.Get<float>(EntityType::Player, Player::Armor);
            return data_view.Get<float>(cached_key);
        }

        inline const VTX::Vector& GetPosition() const {
            static VTX::PropertyKey<VTX::Vector> cached_key = accessor.Get<VTX::Vector>(EntityType::Player, Player::Position);
            return data_view.Get<VTX::Vector>(cached_key);
        }

        inline const VTX::Quat& GetRotation() const {
            static VTX::PropertyKey<VTX::Quat> cached_key = accessor.Get<VTX::Quat>(EntityType::Player, Player::Rotation);
            return data_view.Get<VTX::Quat>(cached_key);
        }

        inline const VTX::Vector& GetVelocity() const {
            static VTX::PropertyKey<VTX::Vector> cached_key = accessor.Get<VTX::Vector>(EntityType::Player, Player::Velocity);
            return data_view.Get<VTX::Vector>(cached_key);
        }

        inline bool GetIsAlive() const {
            static VTX::PropertyKey<bool> cached_key = accessor.Get<bool>(EntityType::Player, Player::IsAlive);
            return data_view.Get<bool>(cached_key);
        }

        inline int32_t GetScore() const {
            static VTX::PropertyKey<int32_t> cached_key = accessor.Get<int32_t>(EntityType::Player, Player::Score);
            return data_view.Get<int32_t>(cached_key);
        }

        inline int32_t GetDeaths() const {
            static VTX::PropertyKey<int32_t> cached_key = accessor.Get<int32_t>(EntityType::Player, Player::Deaths);
            return data_view.Get<int32_t>(cached_key);
        }

    };

    namespace Projectile {
        constexpr const char* StructName = "Projectile";
        constexpr const char* UniqueID = "UniqueID";
        constexpr const char* OwnerID = "OwnerID";
        constexpr const char* Position = "Position";
        constexpr const char* Velocity = "Velocity";
        constexpr const char* Damage = "Damage";
        constexpr const char* Type = "Type";
    }

    class ProjectileView {
    private:
        VTX::EntityView data_view;
        const VTX::FrameAccessor& accessor;

    public:
        ProjectileView(VTX::EntityView view, const VTX::FrameAccessor& acc) 
            : data_view(view), accessor(acc) {}

        ProjectileView(const VTX::PropertyContainer& container, const VTX::FrameAccessor& acc) 
            : data_view(container), accessor(acc) {}

        inline const std::string& GetUniqueID() const {
            static VTX::PropertyKey<std::string> cached_key = accessor.Get<std::string>(EntityType::Projectile, Projectile::UniqueID);
            return data_view.Get<std::string>(cached_key);
        }

        inline const std::string& GetOwnerID() const {
            static VTX::PropertyKey<std::string> cached_key = accessor.Get<std::string>(EntityType::Projectile, Projectile::OwnerID);
            return data_view.Get<std::string>(cached_key);
        }

        inline const VTX::Vector& GetPosition() const {
            static VTX::PropertyKey<VTX::Vector> cached_key = accessor.Get<VTX::Vector>(EntityType::Projectile, Projectile::Position);
            return data_view.Get<VTX::Vector>(cached_key);
        }

        inline const VTX::Vector& GetVelocity() const {
            static VTX::PropertyKey<VTX::Vector> cached_key = accessor.Get<VTX::Vector>(EntityType::Projectile, Projectile::Velocity);
            return data_view.Get<VTX::Vector>(cached_key);
        }

        inline float GetDamage() const {
            static VTX::PropertyKey<float> cached_key = accessor.Get<float>(EntityType::Projectile, Projectile::Damage);
            return data_view.Get<float>(cached_key);
        }

        inline const std::string& GetType() const {
            static VTX::PropertyKey<std::string> cached_key = accessor.Get<std::string>(EntityType::Projectile, Projectile::Type);
            return data_view.Get<std::string>(cached_key);
        }

    };

    namespace MatchState {
        constexpr const char* StructName = "MatchState";
        constexpr const char* UniqueID = "UniqueID";
        constexpr const char* ScoreTeam1 = "ScoreTeam1";
        constexpr const char* ScoreTeam2 = "ScoreTeam2";
        constexpr const char* Round = "Round";
        constexpr const char* Phase = "Phase";
        constexpr const char* TimeRemaining = "TimeRemaining";
    }

    class MatchStateView {
    private:
        VTX::EntityView data_view;
        const VTX::FrameAccessor& accessor;

    public:
        MatchStateView(VTX::EntityView view, const VTX::FrameAccessor& acc) 
            : data_view(view), accessor(acc) {}

        MatchStateView(const VTX::PropertyContainer& container, const VTX::FrameAccessor& acc) 
            : data_view(container), accessor(acc) {}

        inline const std::string& GetUniqueID() const {
            static VTX::PropertyKey<std::string> cached_key = accessor.Get<std::string>(EntityType::MatchState, MatchState::UniqueID);
            return data_view.Get<std::string>(cached_key);
        }

        inline int32_t GetScoreTeam1() const {
            static VTX::PropertyKey<int32_t> cached_key = accessor.Get<int32_t>(EntityType::MatchState, MatchState::ScoreTeam1);
            return data_view.Get<int32_t>(cached_key);
        }

        inline int32_t GetScoreTeam2() const {
            static VTX::PropertyKey<int32_t> cached_key = accessor.Get<int32_t>(EntityType::MatchState, MatchState::ScoreTeam2);
            return data_view.Get<int32_t>(cached_key);
        }

        inline int32_t GetRound() const {
            static VTX::PropertyKey<int32_t> cached_key = accessor.Get<int32_t>(EntityType::MatchState, MatchState::Round);
            return data_view.Get<int32_t>(cached_key);
        }

        inline const std::string& GetPhase() const {
            static VTX::PropertyKey<std::string> cached_key = accessor.Get<std::string>(EntityType::MatchState, MatchState::Phase);
            return data_view.Get<std::string>(cached_key);
        }

        inline float GetTimeRemaining() const {
            static VTX::PropertyKey<float> cached_key = accessor.Get<float>(EntityType::MatchState, MatchState::TimeRemaining);
            return data_view.Get<float>(cached_key);
        }

    };

} // namespace VTX::ArenaSchema