// Tests for VTX::BinaryCursor + VTX::GenericBinaryLoader + VTX::BinaryBinding<Tag>.
//
// Coverage:
//   - BinaryCursor: typed reads, length-prefixed strings, c-strings, sub-cursors,
//     bounds checking (throws on overrun), endian swap.
//   - GenericBinaryLoader: dispatch into BinaryBinding<Tag>::Transfer, walking
//     the cursor with Read<T> and feeding each value through LoadField into the
//     correct PropertyContainer slot.

#include <gtest/gtest.h>

#include "vtx/common/adapters/binary/binary_cursor.h"
#include "vtx/common/readers/frame_reader/binary_loader.h"
#include "vtx/common/readers/schema_reader/schema_registry.h"
#include "vtx/common/vtx_types.h"

#include "util/test_fixtures.h"
#include "util/test_schema_generated.h" // VTX::TestSchema::Player::*

#include <bit>
#include <cstdint>
#include <cstring>
#include <stdexcept>
#include <string>
#include <vector>

namespace vtx_binary_loader_test {

    // Tag for the test entity layout. Each tag is a unique empty struct,
    // analogous to a FlatBuffer-generated type or a protobuf message class --
    // it's just the discriminator for BinaryBinding<>.
    struct BinPlayer {};

    // Pack a synthetic blob for one player. Layout (little-endian):
    //   u16     name_len
    //   bytes   name             (name_len bytes, NOT null-terminated)
    //   bytes   unique_id        (10 bytes, null-terminated c-string)
    //   i32     team
    //   float   health
    //   double  pos.x, pos.y, pos.z
    inline std::vector<uint8_t> BuildPlayerBlob() {
        std::vector<uint8_t> buf;

        auto push_bytes = [&](const void* p, size_t n) {
            const uint8_t* b = static_cast<const uint8_t*>(p);
            buf.insert(buf.end(), b, b + n);
        };

        // u16 name_len = 5, then "Alice"
        uint16_t name_len = 5;
        push_bytes(&name_len, sizeof(name_len));
        push_bytes("Alice", 5);

        // unique_id: 10-byte c-string slot "player_42" + NUL.
        push_bytes("player_42\0", 10);

        int32_t team = 1;
        push_bytes(&team, sizeof(team));

        float health = 75.5f;
        push_bytes(&health, sizeof(health));

        double pos_x = 1.0, pos_y = 2.0, pos_z = 3.0;
        push_bytes(&pos_x, sizeof(pos_x));
        push_bytes(&pos_y, sizeof(pos_y));
        push_bytes(&pos_z, sizeof(pos_z));

        return buf;
    }

} // namespace vtx_binary_loader_test

// The binding spec lives in namespace VTX (qualified specialization).
template <>
struct VTX::BinaryBinding<vtx_binary_loader_test::BinPlayer> {
    static void Transfer(VTX::BinaryCursor& cur, VTX::PropertyContainer& dest, VTX::GenericBinaryLoader& loader,
                         const std::string& schema_name) {
        // The order of Read<T>() calls MUST match the producer's layout.
        // Each value is fed into LoadField with the slot name from the schema --
        // pulled from the autogenerated VTX::TestSchema constants so a rename
        // of the schema is caught at compile time, not silently at runtime.
        namespace P = VTX::TestSchema::Player;

        loader.LoadField(dest, schema_name, P::Name, cur.ReadLenString<uint16_t>());
        loader.LoadField(dest, schema_name, P::UniqueID, cur.ReadCStr(10));
        loader.LoadField(dest, schema_name, P::Team, cur.Read<int32_t>());
        loader.LoadField(dest, schema_name, P::Health, cur.Read<float>());

        VTX::Vector pos {cur.Read<double>(), cur.Read<double>(), cur.Read<double>()};
        loader.LoadField(dest, schema_name, P::Position, pos);
    }
};

namespace {
    std::string SchemaPath() {
        return VtxTest::FixturePath("test_schema.json");
    }
} // namespace

// ===================================================================
//  BinaryCursor: low-level read primitives
// ===================================================================

TEST(BinaryCursor, BasicPodReadsAdvanceCursor) {
    // Layout: u8, u16, u32, float, double
    std::vector<uint8_t> buf;
    uint8_t b = 0xAB;
    uint16_t s = 0x1234;
    uint32_t i = 0xDEADBEEF;
    float f = 3.14f;
    double d = 2.71828;

    auto append = [&](const void* p, size_t n) {
        const uint8_t* bp = static_cast<const uint8_t*>(p);
        buf.insert(buf.end(), bp, bp + n);
    };
    append(&b, 1);
    append(&s, 2);
    append(&i, 4);
    append(&f, 4);
    append(&d, 8);

    VTX::BinaryCursor cur(buf.data(), buf.size());
    EXPECT_EQ(cur.Tell(), 0u);
    EXPECT_EQ(cur.Read<uint8_t>(), 0xAB);
    EXPECT_EQ(cur.Tell(), 1u);
    EXPECT_EQ(cur.Read<uint16_t>(), 0x1234);
    EXPECT_EQ(cur.Read<uint32_t>(), 0xDEADBEEFu);
    EXPECT_FLOAT_EQ(cur.Read<float>(), 3.14f);
    EXPECT_DOUBLE_EQ(cur.Read<double>(), 2.71828);
    EXPECT_TRUE(cur.Eof());
}

TEST(BinaryCursor, BoundsCheckThrowsOnOverrun) {
    std::vector<uint8_t> tiny {0x01, 0x02};
    VTX::BinaryCursor cur(tiny.data(), tiny.size());

    EXPECT_NO_THROW({ (void)cur.Read<uint8_t>(); });
    // Remaining() == 1, asking for 4 bytes must throw.
    EXPECT_THROW({ (void)cur.Read<int32_t>(); }, std::out_of_range);
}

TEST(BinaryCursor, ReadLenStringAndCStr) {
    std::vector<uint8_t> buf;
    auto push = [&](const void* p, size_t n) {
        const uint8_t* b = static_cast<const uint8_t*>(p);
        buf.insert(buf.end(), b, b + n);
    };

    uint16_t len = 3;
    push(&len, 2);
    push("foo", 3);
    push("bar\0baz", 7); // c-string "bar" + NUL + "baz" (not terminated)

    VTX::BinaryCursor cur(buf.data(), buf.size());
    EXPECT_EQ(cur.ReadLenString<uint16_t>(), "foo");
    EXPECT_EQ(cur.ReadCStr(8), "bar");
    // After ReadCStr "bar" + NUL, cursor sits at "baz".
    EXPECT_EQ(cur.ReadString(3), "baz");
}

TEST(BinaryCursor, SubCursorCarvesRegionAndAdvancesParent) {
    std::vector<uint8_t> buf {0xAA, 0x01, 0x02, 0x03, 0x04, 0xBB};
    VTX::BinaryCursor cur(buf.data(), buf.size());

    EXPECT_EQ(cur.Read<uint8_t>(), 0xAA);
    VTX::BinaryCursor sub = cur.SubCursor(4);
    EXPECT_EQ(sub.Size(), 4u);
    EXPECT_EQ(sub.Read<uint8_t>(), 0x01);
    EXPECT_EQ(sub.Read<uint8_t>(), 0x02);
    // Parent has advanced past the slice -- next read is 0xBB.
    EXPECT_EQ(cur.Read<uint8_t>(), 0xBB);
    EXPECT_TRUE(cur.Eof());
}

TEST(BinaryCursor, EndianSwapAppliesToMultiByteArithmetic) {
    // Bytes 01 02 03 04 -- big-endian uint32 == 0x01020304.
    std::vector<uint8_t> buf {0x01, 0x02, 0x03, 0x04};

    VTX::BinaryCursor be(buf.data(), buf.size(), std::endian::big);
    if constexpr (std::endian::native == std::endian::little) {
        // Cursor swaps from big -> native (little).
        EXPECT_EQ(be.Read<uint32_t>(), 0x01020304u);
    } else {
        EXPECT_EQ(be.Read<uint32_t>(), 0x01020304u); // already big
    }

    VTX::BinaryCursor le(buf.data(), buf.size(), std::endian::little);
    if constexpr (std::endian::native == std::endian::little) {
        EXPECT_EQ(le.Read<uint32_t>(), 0x04030201u); // raw little-endian read
    } else {
        EXPECT_EQ(le.Read<uint32_t>(), 0x04030201u); // swap big <- little
    }
}

TEST(BinaryCursor, ConstructsFromSpanOfBytes) {
    // Primary constructor takes std::span<const std::byte>. Verify it interoperates
    // with the common idioms: std::as_bytes() over a typed vector / array.
    std::vector<uint32_t> typed {0xCAFEBABE, 0xDEADBEEF};
    auto bytes = std::as_bytes(std::span<const uint32_t>(typed));

    VTX::BinaryCursor cur(bytes);
    EXPECT_EQ(cur.Size(), 8u);
    EXPECT_EQ(cur.Read<uint32_t>(), 0xCAFEBABEu);
    EXPECT_EQ(cur.Read<uint32_t>(), 0xDEADBEEFu);
    EXPECT_TRUE(cur.Eof());
}

TEST(BinaryCursor, AlignToRoundsUp) {
    std::vector<uint8_t> buf(16, 0x00);
    VTX::BinaryCursor cur(buf.data(), buf.size());

    cur.Skip(3);
    cur.AlignTo(4);
    EXPECT_EQ(cur.Tell(), 4u);
    cur.AlignTo(4);
    EXPECT_EQ(cur.Tell(), 4u); // already aligned -> no-op
    cur.Skip(1);
    cur.AlignTo(8);
    EXPECT_EQ(cur.Tell(), 8u);
}

// ===================================================================
//  GenericBinaryLoader: end-to-end via BinaryBinding<Tag>::Transfer
// ===================================================================

TEST(BinaryLoader, ReadsTypedFieldsFromCursorIntoPropertyContainer) {
    VTX::SchemaRegistry schema;
    ASSERT_TRUE(schema.LoadFromJson(SchemaPath()));

    VTX::GenericBinaryLoader loader(schema.GetPropertyCache());

    auto blob = vtx_binary_loader_test::BuildPlayerBlob();
    VTX::BinaryCursor cursor(blob.data(), blob.size());

    VTX::PropertyContainer dest;
    loader.Load<vtx_binary_loader_test::BinPlayer>(cursor, dest, VTX::TestSchema::Player::StructName);

    EXPECT_GE(dest.entity_type_id, 0);

    // Schema-driven slot indices for "Player":
    //   string[0]=UniqueID  string[1]=Name
    //   int32[0]=Team
    //   float[0]=Health
    //   vector[0]=Position
    ASSERT_EQ(dest.string_properties.size(), 2u);
    EXPECT_EQ(dest.string_properties[0], "player_42");
    EXPECT_EQ(dest.string_properties[1], "Alice");

    ASSERT_EQ(dest.int32_properties.size(), 1u);
    EXPECT_EQ(dest.int32_properties[0], 1);

    ASSERT_EQ(dest.float_properties.size(), 1u);
    EXPECT_FLOAT_EQ(dest.float_properties[0], 75.5f);

    ASSERT_EQ(dest.vector_properties.size(), 1u);
    EXPECT_DOUBLE_EQ(dest.vector_properties[0].x, 1.0);
    EXPECT_DOUBLE_EQ(dest.vector_properties[0].y, 2.0);
    EXPECT_DOUBLE_EQ(dest.vector_properties[0].z, 3.0);

    EXPECT_NE(dest.content_hash, 0u);
    // Cursor fully consumed.
    EXPECT_TRUE(cursor.Eof());
}
